# Model configuration
model:
  # Backbone configuration
  num_classes: 100  # Matches the highest index in class_groups + 1

  
  backbone:
    name: 'resnet50'
    pretrained: true
    out_channels: 256
  
  # System detector configuration
  system_detector:
    hidden_channels: 256
    prior_aspect_ratio: [8.0, 12.0, 16.0]
  
  # Staff detector configuration
  staff_detector:
    hidden_channels: 256
    prior_aspect_ratio: [5.0, 8.0, 10.0]
  
  # Staffline detector configuration
  staffline_detector:
    hidden_channels: 128
    groups: 5  # 5 stafflines per staff
  
  # Element detector configuration
  element_detector:
    hidden_channels: 256
    class_groups:
      macro: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      mid: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
      micro: [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
    anchors_config:
      macro:
        scales: [32, 64, 128]
        ratios: [0.5, 1.0, 2.0, 4.0]
        num_anchors: 4
      mid:
        scales: [16, 32, 64]
        ratios: [0.5, 1.0, 2.0]
        num_anchors: 3
      micro:
        scales: [8, 16, 32]
        ratios: [0.75, 1.0, 1.25]
        num_anchors: 3
  
  # Relationship module configuration
  relationship:
    node_feat_dim: 256
    edge_feat_dim: 128
    hidden_dim: 256
    num_iterations: 3

# Training configuration
training:
  batch_size: 8
  num_workers: 4
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 100
  save_interval: 5
  eval_interval: 5
  warmup_epochs: 5
  lr_scheduler: 'cosine'
  
  # Loss weights
  loss_weights:
    system_cls: 1.0
    system_reg: 1.0
    staff_cls: 1.0
    staff_reg: 1.0
    staffline: 2.0
    element_cls: 1.0
    element_reg: 1.0
    relationship: 0.5

# Inference configuration
inference:
  system_score_thresh: 0.5
  system_nms_thresh: 0.5
  staff_score_thresh: 0.5
  staff_nms_thresh: 0.5
  staffline_thresh: 0.5
  element_score_thresh: 0.3
  element_nms_thresh: 0.5
  relationship_thresh: 0.5

# Data configuration
data:
  annotations_dir: '/homes/es314/omr-objdet-benchmark/data/annotations'
  images_dir: '/homes/es314/omr-objdet-benchmark/data/images'
  resize_height: 1024
  resize_width: 1024
  split_ratio: [0.7, 0.15, 0.15]
  class_map_file: '/homes/es314/omr-objdet-benchmark/class_mapping.json'